FROM rust

RUN apt-get update && apt-get install -y libopencv-dev clang libclang-dev 
#RUN apt-get install -y liblept5 tesseract-ocr tesseract-ocr-eng libtesseract-dev

#libopencv-dev clang libclang-dev
#libleptonica-dev



CMD ["bash"]
