FROM ubuntu

#RUN apt-get update && apt-get install -y python3-opencv python3-numpy python3-matplotlib python3-pip
RUN apt-get update && apt-get install -y python3 curl

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

#RUN pip3 install --no-cache-dir --upgrade pip3 

#RUN pip3 install --break-system-packages --no-cache-dir easyocr imutils

CMD ["bash"]
